#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

if [ ! -d .venv ]; then
    python3 -m venv .venv
fi
.venv/bin/pip install -e ".[dev]"

# Qt's own standard-button strings ("Close", "Cancel", "OK", ...) live in
# Qt's own qtbase_<code>.qm, not this app's mdtools_<code>.qm -- see
# i18n/__init__.py's install_translator() docstring. Located dynamically
# (not a hardcoded .venv path) since PySide6's own install layout can
# shift between versions/platforms.
QT_TRANSLATIONS=$(.venv/bin/python -c "from PySide6.QtCore import QLibraryInfo; print(QLibraryInfo.path(QLibraryInfo.LibraryPath.TranslationsPath))")

# MDTools' own Telegram API ID/Hash are baked in here rather than committed
# to the source tree -- this repo has a public remote, and a credential in
# git history is effectively permanent. Set MDTOOLS_TELEGRAM_API_ID and
# MDTOOLS_TELEGRAM_API_HASH to bake them into this build; leave them unset to
# keep whatever untracked src/mdtools/_build_credentials.py already exists
# locally (which is also what makes a dev-mode run work). See
# app_settings._bundled_telegram_credentials() -- and note this is not secret
# storage: anything a build carries can be recovered from it.
CREDENTIALS_FILE="src/mdtools/_build_credentials.py"
if [ -n "${MDTOOLS_TELEGRAM_API_ID:-}" ] && [ -n "${MDTOOLS_TELEGRAM_API_HASH:-}" ]; then
    echo "Baking in Telegram API credentials from the environment."
    cat > "$CREDENTIALS_FILE" <<EOF
"""GENERATED by scripts/build_linux.sh -- do not commit (gitignored)."""

TELEGRAM_API_ID = "${MDTOOLS_TELEGRAM_API_ID}"
TELEGRAM_API_HASH = "${MDTOOLS_TELEGRAM_API_HASH}"
EOF
elif [ -f "$CREDENTIALS_FILE" ]; then
    echo "Using the existing untracked $CREDENTIALS_FILE."
else
    echo "WARNING: no Telegram API credentials; set MDTOOLS_TELEGRAM_API_ID/_HASH to bake them in." >&2
fi

# No bin/ is bundled here, unlike the Windows build: cdparanoia and flac
# are packaged by every distribution, so cdrip.find_tool() picks them up
# from PATH instead of a bundled copy.
.venv/bin/pyinstaller --noconfirm --windowed --name MDTools --paths src \
    --add-data "src/mdtools/templates/defaults.json:mdtools/templates" \
    --add-data "src/mdtools/i18n/mdtools_pl.qm:mdtools/i18n" \
    --add-data "src/mdtools/i18n/mdtools_ja.qm:mdtools/i18n" \
    --add-data "$QT_TRANSLATIONS/qtbase_pl.qm:PySide6/translations" \
    --add-data "$QT_TRANSLATIONS/qtbase_ja.qm:PySide6/translations" \
    --add-data "assets/img:assets/img" \
    --add-data "assets/icons:assets/icons" \
    src/mdtools/main.py

echo "Build output: dist/MDTools/MDTools"
