$ErrorActionPreference = "Stop"
Set-Location (Join-Path $PSScriptRoot "..")

if (-not (Test-Path ".venv")) {
    python -m venv .venv
}
& ".venv/Scripts/python.exe" -m pip install -e ".[dev]"

# Qt's own standard-button strings ("Close", "Cancel", "OK", ...) live in
# Qt's own qtbase_<code>.qm, not this app's mdtools_<code>.qm -- see
# i18n/__init__.py's install_translator() docstring. Located dynamically
# (not a hardcoded .venv path) since PySide6's own install layout can
# shift between versions/platforms.
$qtTranslations = & ".venv/Scripts/python.exe" -c "from PySide6.QtCore import QLibraryInfo; print(QLibraryInfo.path(QLibraryInfo.LibraryPath.TranslationsPath))"

# xD-Tools' own Telegram API ID/Hash are baked in here rather than committed
# to the source tree -- this repo has a public remote, and a credential in
# git history is effectively permanent. Set MDTOOLS_TELEGRAM_API_ID and
# MDTOOLS_TELEGRAM_API_HASH to bake them into this build; leave them unset
# to keep whatever untracked src/mdtools/_build_credentials.py already
# exists locally (which is also what makes a dev-mode run work).
# See app_settings._bundled_telegram_credentials() -- and note this is not
# secret storage: anything a build carries can be recovered from it.
$credentialsFile = "src/mdtools/_build_credentials.py"
if ($env:MDTOOLS_TELEGRAM_API_ID -and $env:MDTOOLS_TELEGRAM_API_HASH) {
    Write-Host "Baking in Telegram API credentials from the environment."
    $lines = @(
        '"""GENERATED by scripts/build_windows.ps1 -- do not commit (gitignored)."""',
        '',
        "TELEGRAM_API_ID = `"$($env:MDTOOLS_TELEGRAM_API_ID)`"",
        "TELEGRAM_API_HASH = `"$($env:MDTOOLS_TELEGRAM_API_HASH)`""
    )
    $lines | Out-File -FilePath $credentialsFile -Encoding utf8
} elseif (Test-Path $credentialsFile) {
    Write-Host "Using the existing untracked $credentialsFile."
} else {
    Write-Warning "No Telegram API credentials: set MDTOOLS_TELEGRAM_API_ID/_HASH to bake them in. The build works, but users must supply their own to sign in."
}

& ".venv/Scripts/pyinstaller.exe" --noconfirm --windowed --name "xD-Tools" --paths src `
    --icon "assets/img/xdtools.ico" `
    --add-data "src/mdtools/templates/defaults.json;mdtools/templates" `
    --add-data "src/mdtools/i18n/mdtools_pl.qm;mdtools/i18n" `
    --add-data "src/mdtools/i18n/mdtools_ja.qm;mdtools/i18n" `
    --add-data "$qtTranslations/qtbase_pl.qm;PySide6/translations" `
    --add-data "$qtTranslations/qtbase_ja.qm;PySide6/translations" `
    --add-data "assets/img;assets/img" `
    --add-data "assets/icons;assets/icons" `
    --add-data "bin/win64;bin/win64" `
    src/mdtools/main.py

Write-Host "Build output: dist/xD-Tools/xD-Tools.exe"
